services:
  seafile:
    image: ${SEAFILE_IMAGE:?Variable is not set}
    container_name: seafile
    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/seafile:/shared
    environment:
      - SEAFILE_MYSQL_DB_HOST=${MARIA_DB_HOST:?Variable is not set}
      - SEAFILE_MYSQL_DB_PORT=${MARIA_DB_PORT:?Variable is not set}
      - SEAFILE_MYSQL_DB_USER=${SEAFILE_DB_USER:?Variable is not set}
      - SEAFILE_MYSQL_DB_PASSWORD=${SEAFILE_DB_PASSWORD:?Variable is not set or empty}
      - INIT_SEAFILE_MYSQL_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD:?Variable is not set}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=${SEAFILE_CCNET_DB_NAME:?Variable is not set}
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=${SEAFILE_DB_NAME:?Variable is not set}
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=${SEAFILE_SEAHUB_DB_NAME:?Variable is not set}
      - TIME_ZONE=${TIME_ZONE:?Variable is not set}
      - INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL:?Variable is not set}
      - INIT_SEAFILE_ADMIN_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD:?Variable is not set}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      - SEAFILE_SERVER_PROTOCOL=${SERVER_PROTOCOL:?Variable is not set}
      # - SITE_ROOT=${SITE_ROOT:?Variable is not set}
      # - NON_ROOT=${NON_ROOT:-false}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - SEAFILE_LOG_TO_STDOUT=${SEAFILE_LOG_TO_STDOUT:-true}
      - ENABLE_SEADOC=${ENABLE_SEADOC:-false}
      # - ENABLE_GO_FILESERVER=${ENABLE_GO_FILESERVER:-false}
      - SEADOC_SERVER_URL=${SERVER_PROTOCOL:?Variable is not set}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}/sdoc-server
      - CACHE_PROVIDER=${CACHE_PROVIDER:-redis}
      - REDIS_HOST=${REDIS_HOST:?Variable is not set}
      - REDIS_PORT=${REDIS_PORT:?Variable is not set}
      - REDIS_PASSWORD=${REDIS_PASSWORD:?Variable is not set}
      # - MEMCACHED_HOST=${MEMCACHED_HOST:?Variable is not set}
      # - MEMCACHED_PORT=${MEMCACHED_PORT:?Variable is not set}
      # - ENABLE_NOTIFICATION_SERVER=${ENABLE_NOTIFICATION_SERVER:-false}
      # - ENABLE_SEAFILE_AI=${ENABLE_SEAFILE_AI:-false}
      # - ENABLE_FACE_RECOGNITION=${ENABLE_FACE_RECOGNITION:-false}
      # - MD_FILE_COUNT_LIMIT=${MD_FILE_COUNT_LIMIT:-100000}
    # extra_hosts:
    #   - "${ONLYOFFICE_SERVER_HOSTNAME:?Variable is not set or empty}:host-gateway"
    labels:
      caddy: ${SERVER_PROTOCOL:?Variable is not set}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.route_0: /seafdav*
      caddy.route_0.reverse_proxy: "{{upstreams 80}}"
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
      onlyoffice:
        condition: service_healthy
    networks:
      - docker_net
        # aliases:
        #   - ${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}

networks:
  docker_net:
    external: true
