services:
  postgres:
    image: ${POSTGRES_IMAGE:?Variable is not set}
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    # ports:
    #  - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?Variable is not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable is not set}
      - POSTGRES_DB=${POSTGRES_DB:?Variable is not set}
    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/postgres:/var/lib/postgresql
      # - ./NextCloud/init.sql:/docker-entrypoint-initdb.d/nextcloud.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?Variable is not set} -d ${POSTGRES_DB:?Variable is not set} -h localhost -p 5432"]
      interval: 600s
      timeout: 3s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - docker_net

networks:
  docker_net:
    external: true
