services:
    memcached:
      image: ${MEMCACHED_IMAGE:?Variable is not set}
      container_name: memcached
      entrypoint: memcached -m 64
      restart: unless-stopped
      networks:
        - docker_net
networks:
  docker_net:
    external: true
