services:
  ocis:
    image: ${OCIS_IMAGE:?Variable is not set}
    container_name: ocis
    restart: unless-stopped
    user: ${UID:?Variable is not set}:${GID:?Variable is not set}
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; exec ocis server"]
    environment:
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "true"

      OCIS_URL: "${SERVER_PROTOCOL:?Variable is not set}://${OCIS_SERVER_HOSTNAME:?Variable is not set}"

      # OCIS_LOG_LEVEL: error / info / ... / debug
      OCIS_LOG_LEVEL: "info"
      OCIS_LOG_COLOR: "${LOG_PRETTY:-false}"
      OCIS_LOG_PRETTY: "${LOG_PRETTY:-false}"
      PROXY_TLS: "false"

      # make the REVA gateway accessible to the app drivers
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142

      # admin user password
      IDM_ADMIN_PASSWORD: "${OCIS_ADMIN_PASSWORD:?Variable is not set}" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "false"

      # email server (if configured)
      # NOTIFICATIONS_SMTP_HOST: "${SMTP_HOST}"
      # NOTIFICATIONS_SMTP_PORT: "${SMTP_PORT}"
      # NOTIFICATIONS_SMTP_SENDER: "${SMTP_SENDER:-oCIS notifications <notifications@${OCIS_DOMAIN:-ocis.owncloud.test}>}"
      # NOTIFICATIONS_SMTP_USERNAME: "${SMTP_USERNAME}"
      # NOTIFICATIONS_SMTP_INSECURE: "true"

      # make the registry available to the app provider containers
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233

      OCIS_JWT_SECRET: "${JWT_PRIVATE_KEY}"

      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
      # these three vars are needed to the csp config file to include the web office apps and the importer
      # if use onlyoffice
      ONLYOFFICE_DOMAIN: ${ONLYOFFICE_SERVER_HOSTNAME:-onlyoffice.test.localhost}

      # placeholder for now
      COMPANION_DOMAIN: ${COMPANION_SERVER_HOSTNAME:-companion.test.localhost}
      COLLABORA_DOMAIN: ${COLLABORA_SERVER_HOSTNAME:-collabora.test.localhost}

      # enable to allow using the banned passwords list
      # OCIS_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt

      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: "com.owncloud.api.collaboration.CollaboraOnline"
      GRAPH_AVAILABLE_ROLES: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"

    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/ocis/config/app-registry.yaml:/etc/ocis/app-registry.yaml
      - ${BASE_STORAGE_DIR:?Variable is not set}/ocis/config:/etc/ocis
      - ${BASE_STORAGE_DIR:?Variable is not set}/ocis/data:/var/lib/ocis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    
    # make the host machine's gateway available to the container, so that the app provider containers can reach the oCIS server via the host's gateway IP address (which is what they see as the address of the oCIS server)
    # it seems it is needed when using the host.docker.internal address in the app provider containers, otherwise they cannot reach the oCIS server (probably because of some DNS resolution issue), while with this extra_hosts entry, they can reach the oCIS server via the host's gateway IP address
    # might be needed when using localhost domain names like ocis.test.localhost
    # comment them out when using real domain names
    extra_hosts:
      - "${OCIS_SERVER_HOSTNAME:?Variable is not set}:host-gateway"
    networks:
      - docker_net
    labels:
      caddy: ${SERVER_PROTOCOL:?Variable is not set}://${OCIS_SERVER_HOSTNAME:?Variable is not set}
      caddy.reverse_proxy: "{{upstreams 9200}}"

  collaboration-oo:
    image: ${OCIS_IMAGE:?Variable is not set}
    container_name: collaboration-oo
    networks:
      - docker_net
    depends_on:
      ocis:
        condition: service_started
      onlyoffice:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis collaboration server"]

    # it seems it is needed when using the localhost domain names, comment it out when using real domain names
    extra_hosts:
      - "${OCIS_SERVER_HOSTNAME:?Variable is not set or empty}:host-gateway"
      - "${ONLYOFFICE_SERVER_HOSTNAME:?Variable is not set or empty}:host-gateway"
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "ocis:9233"
      COLLABORATION_WOPI_SRC: http://collaboration-oo:9300
      COLLABORATION_APP_NAME: "OnlyOffice"
      COLLABORATION_APP_PRODUCT: "OnlyOffice"
      COLLABORATION_APP_ADDR: ${SERVER_PROTOCOL:?Variable is not set}://${ONLYOFFICE_SERVER_HOSTNAME:?Variable is not set}
      COLLABORATION_APP_ICON: ${SERVER_PROTOCOL:?Variable is not set}://${ONLYOFFICE_SERVER_HOSTNAME:?Variable is not set}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_LOG_LEVEL: info
      OCIS_URL: ${SERVER_PROTOCOL:?Variable is not set}://${OCIS_SERVER_HOSTNAME:?Variable is not set}
      OCIS_JWT_SECRET: "${JWT_PRIVATE_KEY}"
      COLLABORATION_JWT_SECRET: "${JWT_PRIVATE_KEY}"
      COLLABORATION_WOPI_SECRET: "${JWT_PRIVATE_KEY}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    restart: unless-stopped

networks:
  docker_net:
    external: true
