services:
  gitlab:
    image: ${GITLAB_IMAGE:?Variable is not set}
    container_name: gitlab
    restart: unless-stopped
    hostname: ${GITLAB_HOST:?Variable is not set}
    environment:
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL} # User email
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWD} # User password (at least 12 characters)
      GITLAB_OMNIBUS_CONFIG: |
        external_url  "${SERVER_PROTOCOL:?Variable is not set}://${GITLAB_HOST:?Variable is not set}"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/gitlab/config:/etc/gitlab
      - ${BASE_STORAGE_DIR:?Variable is not set}/gitlab/data:/var/opt/gitlab
      - ${BASE_STORAGE_DIR:?Variable is not set}/gitlab/logs:/var/log/gitlab
    shm_size: '256m'
    networks:
      - docker_net
    ports:
      - "2222:22"
      - "${GITLAB_PORT:?Variable is not set}:80"
    labels:
      caddy: ${SERVER_PROTOCOL:?Variable is not set}://${GITLAB_HOST:?Variable is not set}
      caddy.reverse_proxy: "{{upstreams 80}}"

  gitlab-runner:
    image: ${GITLAB_RUNNER_IMAGE:?Variable is not set}
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_STORAGE_DIR}/gitlab/runner-config:/etc/gitlab-runner
    networks:
      - docker_net

networks:
  docker_net:
    external: true
