services:
  hermes-agent:
    &common_settings
    image: ${HERMES_AGENT_IMAGE:?Variable is not set}
    container_name: hermes-agent
    command: gateway run
    environment:
      - HERMES_DASHBOARD=1
      - API_SERVER_ENABLED=true
      - API_SERVER_HOST=0.0.0.0
      - API_SERVER_KEY=${PRIVATE_API_KEY:?Variable is not set}
      # - API_SERVER_CORS_ORIGINS=*
    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/hermes/agent1:/opt/data
    restart: unless-stopped
    ports:
    #   - "8642:8642"   # gateway API
      - "9119:9119"   # dashboard (only reached when HERMES_DASHBOARD=1)
    networks:
      - docker_net
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"

  xflier-agent:
    <<: *common_settings
    container_name: xflier-agent
    ports:
      - "19119:9119"
    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/hermes/xflier:/opt/data

networks:
  docker_net:
    external: true
