services:
  redisinsight:
    image: ${REDIS_INSIGHT_IMAGE:?Variable is not set}
    container_name: redisinsight
    restart: no
    environment:
      - RI_APP_PORT=5540
      - RI_ENCRYPTION_KEY=${JWT_PRIVATE_KEY:?Variable is not set}
      - RI_STDOUT_LOGGER=true
    volumes:
      - ${BASE_STORAGE_DIR:?Variable is not set}/redis/insight:/data
    user: "${UID:?Variable is not set}:${GID:?Variable is not set}"
    ports:
      - "5540:5540"
    networks:
      - docker_net

networks:
  docker_net:
    external: true
