services:
  redis:
    image: ${REDIS_IMAGE:?Variable is not set}
    container_name: redis
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:?Variable is not set}
    networks:
      - docker_net
networks:
  docker_net:
    external: true
